### ISSUE TITLE
feature request - live tv channel sort

### ISSUE THREAD

**Issue by tonyguadagno** [bennettpeter/android-MythTV-Leanfront#17]
Peter,
  I use livetv from time to time and the way channels are sorted is a little confusing....channels that start with a 1..like 10 and 13 all get one line.

would it be possible to sort by major channel  number....like 10.1, 10.2 etc on one line and separate from 13.1,13.2 etc

thanks again for considering.

**Comment by bennettpeter** [comment]
I have it displaying 100 channel numbers per row (0-99, 100-199, 200-299 etc.). I would have done 1 channel per row, but I have hundreds of channels from Comcast. They go from 2 up to 1871 and trying to scroll through hundreds of rows is problematic.

I could add a setting to choose how many channel numbers per row you want. You could set that to 1 so that 10.2 10.2 etc. are together on one row, or set it to 100 for the way it is now, or some other value.

**Comment by tonyguadagno** [comment]
i guess this shows that i am not looking at the bigger picture....i see why you would do it i that way in your circumstance....how hard would it be to make it a user setting to flip between sorting this way and sorting on major channel number?  i guess if it is a real effort, than i will work with it as it is...

i guess it is hard to please everyone!!! LOL

**Comment by jyavenard** [comment]
Hijacking this issue, for me the main problem is that the LiveTV channels appears at the bottom of the screen. I must scroll through hundreds of recordings before I get to be able to enter live TV.

Also missing is the ability to sort recording by times, so that the most recent appears first. This is useful if short of live TV you record a channel and attempt to immediately watch it. It takes dozens of keypresses to find it.

**Comment by bennettpeter** [comment]
Live Channels are treated like a recording group. On the main page is a list of recording groups, and LiveTV is sorted alphabetically in that list. Most people use few recording groups. On my test system, for example,  I have Recently Viewed, All, Default, LiveTV, Peter, Videos. So I only need to down arrow 4 times to get to LiveTV. I don't see where you have to scroll through hundreds of recordings to get to LiveTV. Maybe if you use the All group, but you should rather use the LiveTV group, which contains your prior LiveTV recordings and the channels available.

To sort recordings by time, go to Settings (at the bottom of the screen), Program List Options. You can select to sort by original air date or recording date, and you can select to sort ascending or descending.

**Comment by jyavenard** [comment]
On the left side, there's few recording group, I select livetv and is 6 click down.

From there, I will see lots of recordings started while in livetv. I have thousands. This is a backend with 8TB alocated to mythtv and in use since mythtv 0.15. And I never clean-up :)

It really take over a minute to scroll down to see the livetv channels under 0-99 group and be able to start watching one.
They should be at the top IMHO, and underneath recordings from most recent (eg like the default on the mythtv frontend recordings screen)

These days mythtv is only used for livetv and is recordings typically started while watching livetv. For other type of watching, we would typically use the channel TV app that let you access most content but the live events (sports, music etc)

**Comment by bennettpeter** [comment]
My assumption was that there would not be many recordings in LiveTV, and those would expire soon anyway. Obviously this does not apply to you.

The LiveTV part of leanfront does not have a "record" button facility and does not use the Live TV part of MythTV. LiveTV in leanfront just sets a manual record of fixed duration, waits until it starts recording, then starts watching it. The duration defaults to 60 minutes but can be changed in settings to any value between 30 and 240 minutes. It is not useful for keeping recordings because the name of the recording is just "Live TV" with date and time and it can cross over multiple programs in one recording file. It is more basic than the Live TV feature in mythfrontend.

I could maybe change it so the LiveTV recordings show in a separate group from the TV Channels, if that would be useful. However I think that the LiveTV feature of leanfront is not the best solution for your watching habit.

The search feature may be helpful also. Just go to the search icon at the top. It searches in the guide, the channels and the recordings. Press enter in the entry box and get the keyboard. You can press the microphone while in the keyboard and speak the name of a program or channel number, select Next and it should find it. You can play Live TV from there.

**Comment by bennettpeter** [comment]
For the original request from Tony -
Added a Setting to allow customized number of channels per row, at the end of program list options. Defaults to 100, you can change it to 1 for your purpose, or 10 if that suits you better.  Commit 3b292b7 , not released yet.

**Comment by bennettpeter** [comment]
Feature Released in version leanfront-release-v0-301-gf554f7f.apk
