### ISSUE TITLE
bookmark issue with v32 backend

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#28]
I know things have changed with v32 with bookmarks and last viewed position.  What I see with Leanfront is that if I start watching a recorded program or partially recorded program with mythfrontend and then stop watching and later switch to Leanfront it doesn't give me a choice of viewing from anywhere except the start.  This was not the case with v31 backends. This isn't a major problem for most, but I have the Shield TV icon from Leanfront right next to mythfrontend and this is how I accidentally  found this issue.

**Comment by bennettpeter** [comment]
I am aware of this. I have not changed leanfront. It is still using the bookmark to save the position. There is no API at this time to update the play position from leanfront. I will take a look to see what I should do, but I don't think this is a serious problem.

**Comment by bennettpeter** [comment]
This is fixed in v0-353-g0102ded. This change requires a recent version of master or V32 mythbackend. Also in master or V32, you need to set the port number to 6744 to see the last play position. With older versions or using port 6544 leanfront will work the same as it has always worked, using bookmarks. In a future version of MythTV, probably V33, the port number will revert to 6544 and will support last play position on that port.
