### ISSUE TITLE
Video issue

### ISSUE THREAD

**Issue by shredder83** [bennettpeter/android-MythTV-Leanfront#34]
I've got an Android 11 TV box. I downloaded the latest version of leanfront (20220518-leanfront-release-v0-355-ge675892). Installed OK.
When I start it, it goes straight to the Settings menu, which causes the display to cycle between black scree and Settings page every second or so. Almost like it can't determine the resolution to show on the TV.
If I hit the back button, it will go to the blue background with the Tools menu and icons and look correct. As soon as I go into Settings, same thing again.

I'm new to the Android TV boxes so not sure where to look for logs or how to debug what is going on. All the other apps I have installed have no issues, just leanfront.

Thanks

**Comment by shredder83** [comment]
OK. I got the log. Included here. 
The Settings page does appear during the flickering. I can sort of interact with it, but it seems that when it flashes, it goes back to the main settings page. 
I am also including a video of what is happening.

Hope that helps
[android.log](https://github.com/bennettpeter/android-MythTV-Leanfront/files/8928696/android.log)

https://user-images.githubusercontent.com/24363204/174326958-58233b14-1dc5-4451-9299-e87b768abd3e.MOV

.

**Comment by bennettpeter** [comment]
From the log,

Process : Sending signal. PID: 24056 SIG: 9
ActivityManager: Process org.mythtv.leanfront (pid 24056) has died: fg  TOP 
Zygote  : Process 24056 exited due to signal 9 (Killed)
libprocessgroup: Successfully killed process cgroup uid 10091 pid 24056 in 0ms

For some reason the system is killing the process. Then it restarts it. This happens over and over.

**Comment by shredder83** [comment]
Is there any extra logging that I can get from leanfront itself?
You had said there was a config file I could use to get past the settings screen?

thanks

**Comment by bennettpeter** [comment]
I checked my Shield, it is on Android 11, and I can use settings without any crash.

For setting up manually:
In the git repository there is a file in extras directory, called acopy.sh. Copy to your system. Run it without parameters to see the usage. This uses adb. If it does not work you may have to install the latest adb, which comes with the android sdk. In my experience the version that came with ubuntu was out of date and some things did not work correctly.
Copy settings from the android
`acopy.sh -f <android ip address> --settings`
At this point since settings are not created yet will give you an empty file in /var/tmp/acopy/shared_prefs/org.mythtv.leanfront_preferences.xml
Edit that file and then copy it back to Android this way
`acopy.sh -t <android ip address> --settings`
You only need to set one value in the file to prevent it automatically starting the settings page. Use the correct ip address for the backend:
```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="pref_backend">192.168.0.188</string>
</map>

```
List of tags for settings is here
https://github.com/bennettpeter/android-MythTV-Leanfront/blob/e67589203acd48fe968d35ac8bfb54b62b8e749e/app/src/main/res/values/strings.xml#L67
List of default values for each tag is here. the actual tag names are the name here with "pref" instead of "sdef"
https://github.com/bennettpeter/android-MythTV-Leanfront/blob/e67589203acd48fe968d35ac8bfb54b62b8e749e/app/src/main/res/values/strings.xml#L354

Attached is the file from my shield as an example. (I had to add a txt extension for github to allow file to be attached)
[org.mythtv.leanfront_preferences.xml.txt](https://github.com/bennettpeter/android-MythTV-Leanfront/files/8933584/org.mythtv.leanfront_preferences.xml.txt)

**Comment by shredder83** [comment]
That's a pretty cool tool. 
I got the file downloaded, edited and put back up. I can open LeanFront now and it shows the main screen with the recordings. etc.
But when I try to play a recording, go to Channels, it does the same thing - screen flickers and then brings me back to the main screen.

I've included the log again from when I started the playback.

I appreciate the help. Hope this helps with some debugging.

Thanks
[android.log](https://github.com/bennettpeter/android-MythTV-Leanfront/files/8933983/android.log)
.

**Comment by bennettpeter** [comment]
I think I know what is causing this. I will build a new apk and test it, and make it available to you tomorrow.

**Comment by bennettpeter** [comment]
I have created an interim trial version 20220619-leanfront-trial-v0-357-gaab4c6d.apk. It is in the download site https://dl.orangedox.com/pCBmBm in the "Trial Versions" directory. Let me know if this fixes the problem. This trial version has the bug that you cannot re-launch it after shutting it down without first going into android settings, apps and force-stopping it. If this trial version fixes the problem I will work on getting a version without the re-launch bug.

**Comment by bennettpeter** [comment]
I have tracked down the problem. the problem occurs if I select "Don't keep activities" in developer options. If you have that selected, try unselecting it. I will work on getting it to work with "don't keep activities" selected, as that may occur on some machines.

**Comment by shredder83** [comment]
Ok. Installed the trial version and it worked. Thank you. 

On first use, it seems to work well. Could play a recording, watch live tv.

I’ll start looking through it and see if I can use it as my front end. 

Thanks for taking the time to get it working.

**Comment by bennettpeter** [comment]
I think it may be unstable. I am working on a proper fix for this which will solve any instability you have.

Please tell me, what brand/model of android TV do you have?

**Comment by shredder83** [comment]
It’s a X96X4 android box with Amilogic chip. 
I noticed if I switched it to using ffmpeg the video seemed to buffer less on live TV. Recording seemed to play fine. 

Thanks

**Comment by bennettpeter** [comment]
Please use the new release 20220620-leanfront-release-v0-358-gb8a0f90.apk from the download site. This fixes the issue properly. The trial version was an incomplete fix.

Thank you for bringing this to my attention.
