### ISSUE TITLE
Playback failed on PBS recording

### ISSUE THREAD

**Issue by faginbagin** [bennettpeter/android-MythTV-Leanfront#37]
The exact message is:
Playback Failed.
Error loading data from the MediaSource.
Source error

I've been seeing this problem on a some of my OTA recordings of my local PBS station, WTVS, channel 56.1. But not all. Usually, I can get around it by playing a several seconds on mythfrontend, setting a bookmark and resuming on leanfront. But not on this morning's recording of BBC World News. I had no problem playing the recording on mythfrontend.

I think, but I'm not 100% sure, that it's the reason why I first upgraded from 20220128-leanfront-trial-v0-331-gb1fbde0-dirty.apk to 20220518-leanfront-release-v0-355-ge675892.apk on June 10th. After hitting the problem today, I upgraded to 20220620-leanfront-release-v0-358-gb8a0f90.apk.

I have uploaded the usual diagnostic files to my google drive:
https://drive.google.com/drive/folders/1mtT77n88n_CWH6vWnmCb-37zktPtsk3r?usp=sharing
0623-playback-failed.log - logcat output
0623-playback-failed.png - screenshot of error message
0623-playback-failed.traces - /data/anr/traces.txt
I have also uploaded:
0623-playback-failed.ts - First 100 MB, approx 1:40 of recording
I have confirmed the problem can be reproduced with this file when placed in a video storage group, scanning videos via mythutil and then trying to play from leanfront.

The log should show my two attempts to play the recording. I think the first was between 10:52-10:53 and, where I tried to play from the start. The second was around 10:55 where I tried to play from a bookmark which was around 9 or 10 minutes into the recording.

I think these log entries correspond to my first attempt:
```
06-23 10:52:59.104  4018  6903 E LoadTask: Unexpected exception loading stream
06-23 10:52:59.104  4018  6903 E LoadTask:   java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
```
And these to my second attempt:
```
06-23 10:55:33.790  4018  7129 E LoadTask: Unexpected exception loading stream
06-23 10:55:33.790  4018  7129 E LoadTask:   java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
```
Both are followed by ExoPlayer error messages, so maybe it's their bug and not leanfront's. If that's so, maybe there's an update to ExoPlayer that fixes the problem, or you can report the problem upstream?

There seems to be two of the same exception within milliseconds of each other, perhaps something retries once before giving up? It also looks like I tried twice within a few seconds, although I don't remember doing it.

**Comment by bennettpeter** [comment]
I can recreate this by playing that track from videos.

Exoplayer code is crashing while parsing AC3 audio. That clip has 3 AC3 audio tracks, all seem to be the same when played with vlc. I don't understand how the parsing works. I will do some tests to make sure that nothing in my code is corrupting data, also see if disabling one or more audio tracks prevents it.

I can also upgrade to the latest exoplayer and see if that helps, or add code to disable the offending audio track, or try to skip past the error. The retries in the code already attempt to bypass the error, and it makes more attempts id you select "Continue" when you get the error. That is not helping in this case.

**Comment by faginbagin** [comment]
Thanks for looking into this. I'm relieved that I found something that you can reproduce. Now that you've identified a possible root cause, multiple AC3 tracks, I'll spend some time with other recordings on the same channel using ffprobe and/or mediainfo and see how typical multiple tracks are.

**Comment by faginbagin** [comment]
I think you'll find the 3 audio tracks are a red herring. Everything I've recorded on that station, and still have, has 3 audio tracks. I have over 30 recordings dating back to 9/27/21, when I moved and switched from cable to OTA. This evening, I watched two shows recorded today and both played without problem on leanfront. One was a national broadcast, PBS Newshour, and the other was a local show, One Detroit. Both played without a single hiccup from beginning to end.

**Comment by bennettpeter** [comment]
There must be something different about the AC3 audio on those recordings that fail, and I am wondering if it affects all three audio tracks or only one of them. If the error is caused by one of the tracks, then disabling that one and using one of the others may be a workaround. This is probably not a good solution, as you might end up having to watch in Spanish or with descriptive audio.

**Comment by bennettpeter** [comment]
Currently leanfront is on Exoplayer 2.16.1. The latest version is 2.18.0.
There are some changes in the release notes related to AC3, mostly to do with Dolby Atmos.
At this stage I think the best option is to upgrade leanfront to 2.18.0 and if the problem still exists, open a ticket at exoplayer. I will start work on the upgrade. It is not just a simple switch since I have some customizations and there are deprecated calls that may need to be fixed.

A workaround: Run this against the file to convert it to mkv
`mkvmerge -o 0623-playback-failed_mkv.mkv 0623-playback-failed.ts`
the mkv file plays fine with leanfront, but subtitles are lost if there were subtitles.

Here is a user job I once used to convert to mkv, and it also gets the subtitles. It can be set as a user job in MythTV. It replaces the file in the recording directory so you watch it as usual. The script may be out of date or need some fixing. The ccextractor used here is not the one from MythTV but another one from the internet.
https://github.com/bennettpeter/mythscripts/blob/master/install/opt/mythtv/bin/userjob_mkv.sh

**Comment by bennettpeter** [comment]
I built the exoplayer demo application and the failing file plays correctly there. So something is wrong in leanfront.

**Comment by bennettpeter** [comment]
Please try the package in "Trial Versions" in the download site (20220628-leanfront-release-v0-360-g8e4b423.apk).

This should fix the problem. Let me know if it works for you. If it is ok I will release it generally.

If you have "Settings->Advanced->Show playback error toast" enabled in leanfront, you will see a toast message when the error occurs. The error is bypassed and playback continues. If the messages are troublesome you can disable that setting to suppress the messages. With the sample you gave me there were two messages at the start and none after that. The bypassed errors are also logged in the android log.

**Comment by faginbagin** [comment]
That seems to do the trick. Many Thanks.
