### ISSUE TITLE
some recordings don't play and produce out of memory error

### ISSUE THREAD

**Issue by tonyguadagno** [bennettpeter/android-MythTV-Leanfront#4]
hi, fyi, i have several recordings that when you try to play, spin for about 1 minute and then produce the error in the screenshot.  These are not recordings that have been edited (like other issue).  not sure what is different.  i would be willing to share part of the recording with you, tell me how to get it and give it to you.

thanks  for all your help on this.
![IMG_20200802_171959_HDR](https://user-images.githubusercontent.com/25204879/93021214-83f25480-f5af-11ea-97f0-cf4da98d1226.jpg)

**Comment by bennettpeter** [comment]
Are you using the latest version? I had this same problem and I increased the memory allocation on July 15th (v0-171-gfde6c1b), which fixed it for me. Latest version is  v0-194-g2d2e3de.

**Comment by tonyguadagno** [comment]
Peter, I will try current and let you know

Thanks
!!

Tony

**Comment by tonyguadagno** [comment]
peter, sorry for the delay.  i took your advice and upgraded to latest (201).  i am still having issues with the same recordings, but the message is different:
![IMG_20200928_075726](https://user-images.githubusercontent.com/25204879/94432105-415e7980-0164-11eb-9afd-220d74b72aa9.jpg)

**Comment by bennettpeter** [comment]
Please get me a log when the error occurred:
`adb logcat | tee android.log`
You can put it on pastebin and post a link

**Comment by tonyguadagno** [comment]
peter, it was too big for pastebin, so here is another link to the log
https://drive.google.com/open?id=1af73MajT9rfD9ixjJaMVc_cLDVrPEDdu
let me know if you have an issue getting to it.
thanks

**Comment by bennettpeter** [comment]
I got your log.

I have seen this problem. The player has some problem with the TS container. Can you tell me how this was recorded (type of tuner, over the air or cable, other) and what channel.

You can fix the file using the commands in 
https://github.com/bennettpeter/android-MythTV-Leanfront/blob/master/README.md#problems

Obviously that is not ideal, so I will be looking to see if I can find a solution.

**Comment by tonyguadagno** [comment]
hi, 

```
[    4.400544] media: Linux media interface: v0.10
[    4.407566] Linux video capture interface: v2.00
[    4.459801] saa7164 driver loaded
[    4.459977] CORE saa7164[0]: subsystem: 0070:8880, board: Hauppauge WinTV-HVR2250 [card=3,autodetected]
[    4.459981] saa7164[0]/0: found at 0000:02:00.0, rev: 129, irq: 16, latency: 0, mmio: 0xfb000000

```
OTA recordings...interesting, i looked closer and the recordings that don't play seem all to be from channel 21.2 (rochester ny).  even more interesting, recordings from 21.1 play without issue....

**Comment by bennettpeter** [comment]
I have a similar problem with some recordings from the UK, and it is caused by an empty audio stream. Can you get me an extract from one of those that will not play, or run tsanalyse  on it and send the result. tsanalyse can be installed by downloading and installing tsduck.

**Comment by bennettpeter** [comment]
Here is a version is to fix the recordings from Freeview DVB-T2 or others that will not play with leanfront. Hopefully it will fix your rochester problem as well.

The problem is caused by an empty audio track. There is an audio track called "HE-AAC Audio (eng, visual impaired commentary" that has no audio data. Exoplayer dies when it has filled its buffers and still has no audio data for that track. This fix will initialize the extra audio track with defaults and continue, but only if there was at least one valid audio and one valid video track.

The apk file can be downloaded from here:

https://www.dropbox.com/s/9pqc3z3jqc1t6dg/leanfront-v0-207-g11262a3.apk?dl=1

Let me know if that fixes your problem. If there are no problems with it I will release it on bintray.

Let me know if there are still recordings that cannot be played.

**Comment by tonyguadagno** [comment]
Peter, thanks again for your efforts, I still think you should set up a go fund me so we can contribute.  This version did fix my issues…thanks!


Tony
