### ISSUE TITLE
feature request: Sort recordings by date instead of alphabetic

### ISSUE THREAD

**Issue by kdupke** [bennettpeter/android-MythTV-Leanfront#40]
I see all recordings in alphabetic order. It would be beneficial being able to switch/default to list them by recording time with latest recording on top.

Often Mythtv is used like a time shift recorder. This setting will help to get to the last and most likely requested recordings easily.

In the settings there is a setting for sort by recording time, but it seems this is only for groups of recordings.

**Comment by bennettpeter** [comment]
If I understand you correctly, this is already available in leanfront.
In settings, program list options, Uncheck "Sort by original air date" so that it sorts by recorded date.
Then in the main screen, select the top row (labeled All), and press enter.
You get a screen that says "All" in the top right hand side.
The top row of this screen is all of your recordings sorted by recorded date, oldest first. In my case this row has 1,415 entries, the first being one that was recorded March 3, 2016. The number of entries shows next to the row.
If you rather want the latest recordings to show first in this row, select "Sort Descending" in program list options.

**Comment by kdupke** [comment]
Thank you for reply. 

I do have unchecked 'sort by original air date', as it says 'if unchecked, then sort by recorded date'.

Indeed the top line then lists by recording date, with the latest first.

But the remaining screen below still has all recordings in alphabetic order.

While I can live with this somewhat, what is the benefit of having all horizontal listed by date and vertical by alphabet? On a mobile the second list is an endless scrolling.

Not sure this is by design.

I am OK with this issue getting closed.
