### ISSUE TITLE
Skipping in leanfront

### ISSUE THREAD

**Issue by Jpilk** [bennettpeter/android-MythTV-Leanfront#42]

**Comment by Jpilk** [comment]
I'm not at present using leanfront much because I don't have functioning hdmi audio  hardware.  I'm opening this in response to the invitation on the mythtv users list yesterday, which followed earlier discussions there.

In mythfrontend playback the cutlist is always active.  It can be cleared, pasted from the commflag list, or set or modified by the cutlist editor.  

Normal playback will skip over cuts.  When skipping, the destination is calculated by ignoring the sections of the file that have been defined as cuts.  This might be seen as more user friendly than the current behaviour of leanfront. 

The relevant mythfrontend code seems to be using m_deleteMap in /mythtv/libs/libmythtv/mythplayer.cpp

**Comment by bennettpeter** [comment]
I could make the cut list always skip, unlike the skip list, which is only active if you request it. I would make that an option. so that you can still turn it all off and ignore both lists. However, what is the use case for this? The cut list takes precedence anyway, so if you turn on the option you will have the cut list skips.

As far as the play time is concerned, do you want the cut list to adjust the play time on the progress bar to the reduced time that takes cuts into account? This is more difficult.

For audio, you can also bluetooth speakers or get an HDMI audio extractor. Some devices (e.g. shield) can also take a USB audio adapter.

**Comment by Jpilk** [comment]
Thanks for the suggestions about HDMI audio.

Almost all my playback in 'audience' mode is of files with empty cut/skip lists, so I have no strong feelings about  how leanfront should handle either list.   The mythfrontend way seems logical, if it can be ported.  But viewing habits and preferences vary...

**Comment by Jpilk** [comment]
OT:  Re the audio issue:  I now have a ' Pure Elan DAB+ ' (radio receiver with bluetooth)  about 30 cm from the firestick 4K, with its headphone socket feeding the stereo system.  It works, sort of.  But in playback of recorded BBC SD and HD TV test cards the 'ticks' for audio sync are strange.  Two play as ticks, and the rest are 'shushing' noises, with both MythTV frontend and leanfront, and all the options I have tried.   In Fedora they all play as ticks.  Direct playback of DAB radio is fine.

I haven't yet tried bluetooth headphones.   I'm not clear whether the effect arises in the firestick, bluetooth, or the new box.

**Comment by bennettpeter** [comment]
I am closing this for now. I am not trying to duplicate what mythfrontend does. If somebody is using leanfront and has a reason for wanting to change the way it works I will reconsider it.
