### ISSUE TITLE
feature request: please indicate when you have skipped

### ISSUE THREAD

**Issue by tonyguadagno** [bennettpeter/android-MythTV-Leanfront#43]
hi, first...THANK YOU!!!!!  I love this feature!

now, it seems that at some points, it is not skipping in the same way that the full frontend does, but it is hard to tell.  the standard frontend indicates when it has skipped and for how long, this would be very helpful in figuring out if it is skipping in the right place.

would this be hard to implement?

i am requesting that you indicate when you have skipped and for how long.

thanks again

**Comment by bennettpeter** [comment]
I actually made it so that the skip would be as unnoticeable as possible, thinking that would make a better experience.

I could add a *toast message after each skip, saying that is has skipped and for how long. Probably I would add a setting to make this optional in case not all people like it.

*Toast messages appear in a cloud for about 10 seconds at the bottom of the screen.

**Comment by tonyguadagno** [comment]
peter, if its not too much effort, i think it would be helpful and yes, a setting would be great.  I have noticed that the regular frontend seems to "stick the landing" while leanfront seems to be about 4 or 5 seconds prior to the transition.  I am trying to compare with the same show/episode to get a better handle on it.

thanks again

**Comment by bennettpeter** [comment]
In a new version released yesterday I have added settings to adjust the start and end of skips so if you find they are too soon or too late you can add a few seconds to make them later or subtract a few seconds to make them sooner.

**Comment by bennettpeter** [comment]
Message for "commercial break skipped" is now added to version 20221125-leanfront-release-v0-396-g0e39d23.
