### ISSUE TITLE
Skip button issue

### ISSUE THREAD

**Issue by m01928** [bennettpeter/android-MythTV-Leanfront#48]
With the latest version I can't press the skip button to jump 5 minutes. Instead I get the message "There is no commercial Break or Cut List Data for this Recording."

**Comment by bennettpeter** [comment]
I changed it so that the skip button is for commercial skip and the step button is for jump 5 minutes. You can also customize the up/down buttons to be jump.

I did not know anybody was using a remote with skip buttons.. Please tell me what type of remote you have and what buttons it has.

I can revert those buttons to the normal jump function and use a different method for handling commercial skip.

**Comment by bennettpeter** [comment]
I have posted a new package in "Trial Versions"
20221201-leanfront-release-v0-398-g3a6b388
This switches skip with step, so it should restore the action of the skip buttons and move the commercial skip to the step buttons. Let me know if this solves your problem.

**Comment by m01928** [comment]
I am using a TiVo Stream 4K. The remote only has up, down, left, right and a skip button. The remote can be seen here: https://explore.tivo.com/how-to/stream-4k/remote
Here is an image of the remote:
![Stream4K_Remote_Buttons](https://user-images.githubusercontent.com/119553278/205206791-765c0aec-e15b-4e30-b23c-5ca312968265.png)

I tried the new version and it fixes my issue. Thanks

**Comment by bennettpeter** [comment]
I have moved the trial version to the main download area.
