### ISSUE TITLE
Audio Sync 

### ISSUE THREAD

**Issue by jksj461** [bennettpeter/android-MythTV-Leanfront#6]
leanfront-v0-207-g11262a3
UK dvb-s2 1080i recordings
Audio sync is stable during playback and recovers pretty quickly on starting or resuming playback.
However right arrow (skipping forward) causes losses of sync which can be recovered with left arrow.
So when skipping adds you generally have to do a back after arriving at the desired point.
I remember the front end behaving similarly in version 31 pre but it did get fixed.

**Comment by bennettpeter** [comment]
I have never noticed this problem. Often after skipping forward the sound goes off for a few seconds and then starts up again, but always in sync. Can you please provide a sample recording. Also, what is the device you are using - fire stick, shield, other, etc.?

**Comment by jksj461** [comment]
Wierd cannot reproduce today although the issue has happened many times before.
My main viewing platform is Shield TV. Fire Tv 4K used less often and not on a big TV so less critical.
I have shared the worst offending sample with you for debuging.
It has just occurred to me that we were watching this while it was being  recorded (close to the end stop) which may be relevant to the issue. Will test further.
The issue is compounded with the sample as the wrong audio track is automatically read. I note VLC does the same but mythfrontend at least on PC gets it right. Can't currently test the frontend on Android due to other issues.
When attempting to play the program on Fire Tv it crashes when attempting to change audio track will get logs if you cannot re-produce.
Note does not crash on Shield but audio track reverts to track 1 [NAR] every time the catch up point is reached.

**Comment by bennettpeter** [comment]
I got the sample. mediainfo rells me the first audio track is in English, and the second audio track is language code nar. I looked it up, nar is the code for the Iguta language, which is spoken in Nigeria. When I play the file you sent me it starts up on the English track. Is that wrong?

I have had one recording where it started up on the wrong audio track, and it was because there was a small amount of corrupt audio recording right at the beginning so it switched to the other audio track. Could this be the case? Is it a one-time occurrence?


The first audio track is AC3 and the second is mpeg1 level2. Maybe the fire stick does not support that out of date format. You can actually watch it successfully on audio track 2 if you first select ffmpeg in the audio setup of the settings. I will see if I can fix it so that it does not crash if that happens, and preferably should automatically select ffmpeg when you select an unsupported track.

Regarding the sync problem. I have already got code to handle it. The way it works is, at the start of playback or after skip forward _near the end of a recording in progress_, after 5 seconds you will notice a brief outage (1 tenth of a second) in the sound, after which it will be in sync. Have you tried waiting 5 seconds after forward skip to see if this happens?

**Comment by bennettpeter** [comment]
Further update - 
If you select Mediacodec in the audio settings, it works a bit differently - it may be better for you. Starting playback of your sample selects the nar audio track by default (not sure why) and that is silent since fire stick does not support MP2 audio. Then switching audio tracks works fine, it plays the english track and switching again gives an error message for the "nar" track, but does not crash playback.

Fire stick page confirms mp2 is not on the list of supported audio formats:
https://developer.amazon.com/docs/fire-tv/device-specifications-fire-tv-stick.html?v=ftvstick4k

**Comment by jksj461** [comment]
Many thanks
Please note that this sample is not the normal it must be some sort of edge case within the UK DVB specification. The issue only occurs on a subset of programs within Channel 4 HD programs. Possibly from a single producer. 
Out of interest Mythfrontend reports 
1:Narrative (Audio Description)
2:English AC3 2ch
and plays track 2.
----
leanfront-v0-216-g48b40f7.apk 
Testing on F4K with ffmpeg audio
Works perfectly auto selecting the correct audio track - Audio track 1 enabled
It is possible to select Audio track 2 (Nar) as well

On Shield the correct audio track is now played as default  with Auto setting for audio.
Brilliant

Selecting mediacodec on F4K works as you describe but would lower WAF as it is silent without intervention.
Is there a downside to leaving the F4K in ffmpeg. I am only using it on a stereo tv but would it affect surround sound otherwise?

**Comment by bennettpeter** [comment]
Leaving it set in ffmpeg mode is fine. The only downside is that surround sound will not work, but that is moot if you are only using stereo.

**Comment by jksj461** [comment]
The audio sync issue is still there for some recordings (back arrow required after skipping). The samples you have access to don't exhibit the issue, i will try and narrow it down over the next week to some sort of common factor.
Playback is completely acceptable though. The only scenario to be avoided is trying to skip in a program currently being recorded this currently has low WAF.

**Comment by bennettpeter** [comment]
Audio sync issue: It will help if you can let me know:
- When it is out of sync, is the recording length that is displayed on the right in the OSD shown as an actual value or as --- ?
- When it is out of sync, does it fix it if you change audio channels until you get to audio disabled and then change to the correct audio channel again?
- Is it only on programs still being recorded that you have the problem?

**Comment by jksj461** [comment]
The pattern that is developing is that the issue occurs fairly late on in the evening, after watching about 3 hours of different material. Programs which played perfectly earlier then show the issue. Exiting the program does not resolve. Resetting the Shield does. Apologies did not do the specific tests you mention will try again tomorrow.
Seems highly unlikely but it does fit previous experience that the stuff watched late at night shows the issue.
I know it sounds ridiculous.

**Comment by jksj461** [comment]
When it is out of sync, is the recording length that is displayed on the right in the OSD shown as an actual value or as --- ? Actual value
    When it is out of sync, does it fix it if you change audio channels until you get to audio disabled and then change to the correct audio channel again? Yes
    Is it only on programs still being recorded that you have the problem? No
Ok after a week of use performance has been excellent and very usable  many thanks.
Most testing on Shield TV only occasional use on FireTV & F4K.
Sync problems only occur when skipping forward and are fixed by a single back seek or changing audio track. They occur more often later at night probably due to less structured use ie jumping around skipping parts rather than just watching.
It would be useful to be able to suppress the error messages when decoder errors occur. As this reduces WAF more than the visual glitch.  
Skipping adds in a program that is still recording is the most likely scenario to cause problems. In the worst case decode errors occur accompanied by the error message and the control bar is then displayed making a minor glitch major. Leaving the recording to complete and then playing is perfectly error message free so it hard to understand the problem.
i cannot produce the issue watching live TV which I would have thought would be the same.
Tried to get a log of the glitching but cannot make it happen when I want to.

**Comment by bennettpeter** [comment]
I could add a setting to suppress the decoder error messages when it is a temporary error. When repeated decoder errors occur it displays a message box asking if you want to continue. That will have to stay, to prevent an endless loop of unrecoverable errors.

I have not seen the audio sync problem the way you describe, probably because I use fire stick for watching most of the time. I will take a look into what to do about them.

**Comment by jksj461** [comment]
Sounds good - I have never seen the message box as described as above.

**Comment by bennettpeter** [comment]
Here is a package for you to test. I want to confirm the audio sync problem is fixed before I distribute it generally.
https://www.filezzz.com/d/1c1f690975574887a7347dc9cd8d42ce/leanfront-v0-220-g9dcb478-dirty.apk/preview
There are two changes:
- decode errors during playback will not be displayed unless you enable a new setting under settings->playback.
- after each seek the audio is disabled and enabled. This is equivalent to changing audio track, so it should resolve the sync issue.

Let me know if this fixes the problems.

**Comment by jksj461** [comment]
Wow seems like a complete fix. Tested on Shield skipping round a few worst case files.
Had a quick look on FS4K which did not have the same issues and no regression there.
Will test thoroughly tonight but looking very good.
Many thanks

**Comment by jksj461** [comment]
After a full evenings testing the issue seems to be completely resolved.

**Comment by bennettpeter** [comment]
This fix is causing an exception if you hold down the forward button to advance through the recording. I am preparing an update.

**Comment by bennettpeter** [comment]
I have changed the way this works in 0428d75 . In the new version there could be a 5 second delay after seek before the sync is fixed. Please download leanfront-v0-222-g0428d75.apk and test to make sure it is still OK.
