### ISSUE TITLE
Undeleting a currently recording program

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#76]
So I started watching a recording that was in progress and I was about 30 minutes behind real time.  It was supposed to be the Georgia vs. Georgia Tech football game, but what I saw was the end of another game.  So then the end of that game happened, I forgot what I was really doing and deleted that recording.  About a half second later I realize what a dumbbell I was I went back to the delete group and undeleted it.  That didn't work as it does for a completed recording.  The way I recovered was to switch to mythfrontend for Android and go the upcoming recordings and select the game and then select restart recording.

Maybe something can be added to Leanfront the help out football watchers who have had too much to drink while trying to watch football?

**Comment by bennettpeter** [comment]
I think the best solution is to prevent deleting a recording still in progress. That way you would have to first Stop Recording, then delete it.

**Comment by jfabernathy** [comment]
Maybe the best solution is not delete anything until the next morning when I'm drinking coffee.

**Comment by jfabernathy** [comment]
It's not like I'm short on storage.

**Comment by bennettpeter** [comment]
The delete happens immediately. I made it that way because If you made a mistake you can also undelete immediately after deleting. However if you delete something that is recording you do not have that option, the recording is canceled. Rather than adding a "Are you sure" dialog I think it is better to prevent deletion of something that is busy recording, unless they first stop recording.
