### ISSUE TITLE
REQUEST: Navigation Enhancements

### ISSUE THREAD

**Issue by kmand** [bennettpeter/android-MythTV-Leanfront#96]
With a very long vertical ALL list, it's slow to descend down the list to correct row for a title. Some Suggestions:

1) The FF/REW buttons are unused in this context. Have them do longer jumps then the up/down arrows.
2)  I record some daily programs that I want to watch in order. The top horizontal row only shows one episode for each title (the most recent). Add an item to Other Actions that send you to the row in ALL for that title.
3) In the vertical ALL list each row has an option list.  Add an option "Favorite" that positions it before the  alphabetic rows.

**Comment by bennettpeter** [comment]
1. FF/REW buttons. I have implemented this in version 507 (v0-507-g9ff75d3-m1.2.1-2-gc3114cd837). FF and REW now work in the main list left column, also for scrolling left and right in the episode icons (right column), and for scrolling up and down in the program guide.  The FF/REW fast scroll also works in "related videos" on the video details page.

2. Instead of your request number 2 I suggest the following. You can get the full list of episodes as follows: Click on an item in the All row. See the detail screen for the first episode. Press down arrow twice. See a full list of all episodes under "related videos". From this list you can select an episode and watch it. Note that there are options in the Settings page to customize the "related videos" list. 

3. Instead of your request number 3 I suggest the following. To get your favorites easily accessible I recommend using Recording Group. You can press menu (or long press enter) on the row header (left hand column with series titles) and "Update Recording Group". This will change the entire series to a new recording group. Now you can find your favorites in a recording group with a a name of  your choice. Remember to also update the recording rule to set the new group on future recordings.

Another way for finding your favorite series. In the recently viewed list at the top, you can use "related videos". Select a recently viewed episode, press down twice, and see all episodes of that series. Presumably your favorites are series you have watched recently. There are options for the recently viewed list in the Settings. If you cannot see the recently viewed list it may have been disabled in Settings.
